# Application Configuration
# You can specify multiple directories to search for PDF payslips, separated by commas.
payslips.directories=payslips

# The name or path of the generated report file
report.file=hours_report.txt
